quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=dimitrije
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mmorpg
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true 

quarkus.oidc.auth-server-url=http://localhost:8080/realms/MMORPG
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=JwNcA2iTH7PjfhN3MVy1o0DWnWq0nqH6
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.http.port=8081